export const footerLinks = [
  {
    heading: "Investor Relations",
    links: [
      "Performance Highlights",
      "Annual General Meeting",
      "Postal Ballot",
      "Financials",
      "Chairman’s Address",
      "Shares",
      "Transfer of shares to IEPF",
      "Notice to Shareholders to update KYC Details",
      "Code of Conduct",
      "Vigil Mechanism",
      "Policies",
      "Terms & Conditions of Appointment of Independent Directors",
      "SDD",
      "Disclosures",
      "Concall Invite",
      "Unpaid Dividend",
      "Top Shareholders",
      "Familiarisation Programme imparted to Independent Directors",
      "Non-Convertable Bonds & Trustees",
    ],
  },
  {
    heading: "Company",
    links: [
      "About us",
      "Vision",
      "Careers",
      "Background & History",
      "Board and Organisation",
      "Swachh SAIL Sundar SAIL",
      "Climate Action India- Climate Change & SAIL",
      "Company Policies",
      "Awards & Accolades",
      "Our Employees",
    ],
  },
  {
    heading: "Marketing",
    links: [
      "Buy SAIL SeQR Online",
      "Central Marketing Organisation",
      "Demand Registration Scheme for Nepal customers",
      "Distributor - Dealer Network",
      "Exports",
      "Product Applications",
      "SAIL Network Map",
      "All India Demand Registration of SAIL Steel 2023-24-English",
      "All India Demand Registration of SAIL Steel 2023-24-Hindi",
      "Customer Feedback",
      "Customer Testimonial",
      "MOU Policy for Stainless Steel 2023",
      "Monthly supply position of WTA to Indian Railways",
    ],
  },
  {
    heading: "Corporate Citizenship",
    links: [
      "Corporate Citizenship",
      "Sustainability Report",
      "Integrity Pact",
      "Peripheral Development",
      "Education",
      "CSR Provisions of Companies Act-2013",
      "SD Projects for SAIL 2019-20",
      "Citizen's Charter",
      "Human Rights Charter",
      "Medical and Health Care",
      "Personnel Policies",
    ],
  },
  {
    heading: "Important Links",
    links: [
      "Important Links",
      "Vigilance",
      "Tenders",
      "Right to Information Act",
      "Portal for Public Grievances",
      "Pensioners' Portal",
      "Whistle Blower Policy",
      "Steel Links",
      "FAQ",
      "Market Tracker",
      "Learning Center",
    ],
  },
];
